Add testing to controllers
Josphat205/blog-project pull request #5
Opened 2022-10-04 18:04 UTC by Josphat205

## In this pull request

- Added RSpec test to posts and users controllers

2022-10-04 18:16 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @Josphat205👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-04 18:16 UTC, thecodechaser commented on spec/requests/posts_spec.rb
> +  end
- [ ] For this action please include a test for `If the response body includes correct placeholder text`.

2022-10-04 18:16 UTC, thecodechaser commented on spec/requests/posts_spec.rb
> +    end
- [ ] For this section please include the tests for `If a correct template was rendered` and `If the response body includes correct placeholder text`.

2022-10-04 18:16 UTC, thecodechaser commented on spec/requests/users_spec.rb
> +    end
- [ ] For this action please include a test for `If the response body includes correct placeholder text`.

2022-10-04 18:16 UTC, thecodechaser commented on spec/requests/users_spec.rb
> +  end
- [ ] For this action please include a test for `If the response body includes correct placeholder text`.

2022-10-05 06:38 UTC, sja-thedude requested changes
## Invalid Code Review Request ❌

Hi @Josphat205, This is @sja-thedude your code reviewer.

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, that doesn't have linters setup correctly. Make sure all linters are passing.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-10-05 06:56 UTC, merged